### ISSUE TITLE
Could you please make QuickStart using Vue?

### ISSUE THREAD

**Issue by wann2** [AgoraIO-Community/Agora-Electron-Quickstart#10]
Could you please make QuickStart using Vue?

**Comment by plutoless** [comment]
we do have one here, https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/tree/implement-in-vue

**Comment by En777** [comment]
the agora electron sdk vue demo branch can not working,
npm run dev, error:
Uncaught ReferenceError: module is not defined
    at renderer.js:1

**Comment by En777** [comment]
Uncaught ReferenceError: require is not defined
    at (index):5

**Comment by plutoless** [comment]
@En777 sorry for late reply. for electron 5.x you have to provide webPreference: {nodeIntegration: true}
