### ISSUE TITLE
npm install之后本地可以跑起来，打包64位的win正常，打包32位报错

### ISSUE THREAD

**Issue by denglouhen** [AgoraIO-Community/Agora-Electron-Quickstart#104]
1、npm install
2、npm run start正常
3、npm run dist:win64 在文件夹中双击执行exe正常
4、npm run dist:win32 在文件夹中双击执行exe， 报错：
![image](https://user-images.githubusercontent.com/26452618/186376010-bf97f2c5-54be-42c2-bd9e-836e6cc63290.png)

我执行了npm i electron --arch=ia32， 然后npm run start，本地都报那个错误，npm run dist:win32依旧还是错的。
咋整啊？有没有大哥知道啊

**Comment by denglouhen** [comment]
没事了，src下的那个node_modules也要删掉才行

**Comment by denglouhen** [comment]
我在.npmrc里面加上了arch=ia32，安装后npm run start正常，打包32位正常，但是打包出来64又不正常了，报一样的错误。咋整啊

**Comment by plutoless** [comment]
@denglouhen .npmrc只影响你项目里的node_modules，打包需要在打包配置里单独配置，你说的打包出来64不正常，是说打64位的包不正常还是打出来的包在64位的环境下不正常?

**Comment by denglouhen** [comment]
> @denglouhen .npmrc只影响你项目里的node_modules，打包需要在打包配置里单独配置，你说的打包出来64不正常，是说打64位的包不正常还是打出来的包在64位的环境下不正常?

打出来的包，在64位环境下运行不正常。我在声网的论坛里得到了回复，说是不支持同时打32位和64位的包，需要分别npm install之后单独打。谢谢大佬回复我，没事了。

**Comment by plutoless** [comment]
@denglouhen 
是我记错了，应该是用32位的sdk，打32位的程序，在32位和64位的机器都能跑
用64位的sdk打64位的程序，只能在64位的机器跑
但sdk的arch和应用的arch必须匹配

**Comment by denglouhen** [comment]
> @denglouhen 是我记错了，应该是用32位的sdk，打32位的程序，在32位和64位的机器都能跑 用64位的sdk打64位的程序，只能在64位的机器跑 但sdk的arch和应用的arch必须匹配

好的，明白了，谢谢大佬~
