### ISSUE TITLE
请问这个项目还有人维护吗？windows环境总是有错误，没人解答吗？

### ISSUE THREAD

**Issue by denglouhen** [AgoraIO-Community/Agora-Electron-Quickstart#105]
有人解决过吗？代码下载下来，npm install之后，run start可以，打包dist:win64正常，win32报错。把electron换成32位的，结果win32正常，win64的包打开报错。我服了。
有人能正常在windows 64位环境下成功打出可成功运行的win32以及win64的包吗？

**Comment by luz33c** [comment]
https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/issues/104 跟这个问题重复了吧？

当前项目Agora-Electron-API-Example需要分别打包，dist：xx只对当前electron有效，window下打包agora-electron-sdk需要在package.json中指定arch（https://docs.agora.io/cn/video-legacy/start_call_electron?platform=Electron），实际项目中用agora-electron-sdk也参考官方文档

**Comment by denglouhen** [comment]
> #104 跟这个问题重复了吧？
> 
> Agora-Electron-API-Example目录中，dist：xx只对当前electron有效，window下打包agora-electron-sdk需要在package.json中指定arch（[https://docs.agora.io/cn/video-legacy/start_call_electron?platform=Electron），实际项目中用agora-electron-sdk也参考官方文档](https://docs.agora.io/cn/video-legacy/start_call_electron?platform=Electron%EF%BC%89%EF%BC%8C%E5%AE%9E%E9%99%85%E9%A1%B9%E7%9B%AE%E4%B8%AD%E7%94%A8agora-electron-sdk%E4%B9%9F%E5%8F%82%E8%80%83%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3)

嗯嗯，我关掉它
