### ISSUE TITLE
您好,WindowPicker中的代码是React

### ISSUE THREAD

**Issue by lalofuzi** [AgoraIO-Community/Agora-Electron-Quickstart#16]
Agora-Electron-Quickstart implement-in-vue 中WindowPicker下的代码是用React写的,屏幕共享的预览和选择用的还是React写的.这个demo的屏幕共享功能没法实现.

**Comment by lalofuzi** [comment]
快速开始demo选择 implement-in-vue  在src/renderer/components/WindowPicker下是的,您可以打开看看.

**Comment by plutoless** [comment]
@lalofuzi 那个文件我们并没有用到，忽略就好
