### ISSUE TITLE
卡住了 集成sdk报错 

### ISSUE THREAD

**Issue by w493189140** [AgoraIO-Community/Agora-Electron-Quickstart#18]
报错信息  
![image](https://user-images.githubusercontent.com/22770789/69123349-1afb9680-0adc-11ea-85b3-49fdd6c75dfd.png)

安装node-gyp rebuild --target=0.29.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell
安装报错  找不到方法  
![image](https://user-images.githubusercontent.com/22770789/69123425-4bdbcb80-0adc-11ea-9e1d-423552468214.png)
走不下去了  好难啊

**Comment by plutoless** [comment]
@w493189140  package.json的内容发一下。这边为什么在手动指定node-gyp? 我们提供了预下载的包的，不需要你手动编

**Comment by w493189140** [comment]
出现第一张图的报错

**Comment by w493189140** [comment]
{
  "name": "elctron-teacher",
  "version": "0.0.1",
  "author": "cheng <wangcheng55555@163.com>",
  "description": "ygwo-teacher of electron",
  "license": null,
  "main": "./dist/electron/main.js",
  "scripts": {
    "build": "node --max_old_space_size=8192 .electron-vue/build.js && electron-builder",
    "build:dir": "node .electron-vue/build.js && electron-builder --dir",
    "build:clean": "cross-env BUILD_TARGET=clean node .electron-vue/build.js",
    "build:web": "cross-env BUILD_TARGET=web node .electron-vue/build.js",
    "dev": "node .electron-vue/dev-runner.js",
    "pack": "npm run pack:main && npm run pack:renderer",
    "pack:main": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.main.config.js",
    "pack:renderer": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.renderer.config.js",
    "postinstall": ""
  },
  "build": {
    "productName": "阳光教师",
    "appId": "com.electron.elctron-teacher",
    "asar": false,
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "mac": {
      "icon": "build/icons/icon.icns"
    },
    "win": {
      "icon": "build/icons/icon.ico"
    },
    "linux": {
      "icon": "build/icons"
    }
  },
  "dependencies": {
    "agora-electron-sdk": "^2.9.0-hotfix.2",
    "axios": "^0.18.0",
    "better-scroll": "^1.15.2",
    "echarts": "^4.4.0",
    "element-ui": "^2.12.0",
    "less": "^3.10.3",
    "less-loader": "^5.0.0",
    "qs": "^6.5.2",
    "swiper": "^4.3.5",
    "vue": "^2.5.16",
    "vue-calendar-component": "^2.8.2",
    "vue-cropper": "^0.2.9",
    "vue-electron": "^1.0.6",
    "vue-image-crop-upload": "^2.3.3",
    "vue-lazyload": "^1.3.3",
    "vue-resize-sensor": "^2.0.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "vuex-electron": "^1.0.0",
    "wangeditor": "^3.1.1"
  },
  "devDependencies": {
    "ajv": "^6.5.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "babili-webpack-plugin": "^0.1.2",
    "cfonts": "^2.1.2",
    "chalk": "^2.4.1",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.1.6",
    "css-loader": "^0.28.11",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^2.0.18",
    "electron-builder": "^20.19.2",
    "electron-debug": "^1.5.0",
    "electron-devtools-installer": "^2.2.4",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "0.4.0",
    "multispinner": "^0.2.1",
    "node-loader": "^0.6.0",
    "style-loader": "^0.21.0",
    "url-loader": "^1.0.1",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^15.2.4",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.15.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.3"
  }
}

**Comment by plutoless** [comment]
electron须要使用 1.8.3/3.0.6/4.2.8/5.0.8 4个版本
然后在package.json里指定

```
// package.json
{
...
  "agora_electron": {
    "electron_version": "5.0.8", <- 指定你的Electron版本，我们会下载对应的包
    "prebuilt": true
  }
...
}
```

**Comment by w493189140** [comment]
![image](https://user-images.githubusercontent.com/22770789/69209504-6d978a00-0b92-11ea-8035-2fbf5e06e0e9.png)
现在sdk都装不上了  这是什么原因

**Comment by w493189140** [comment]
把node_modules全部删掉  只装agoraSDK 也报错

**Comment by w493189140** [comment]
直接放package.json 装也是一样

**Comment by plutoless** [comment]
只支持上面说的4个版本，你package.json怎么填的？

**Comment by w493189140** [comment]
{
 ...........
  "build": {
    "productName": "阳光教师",
    "appId": "com.electron.elctron-teacher",
    "asar": false,
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "mac": {
      "icon": "build/icons/icon.icns"
    },
    "win": {
      "icon": "build/icons/icon.ico"
    },
    "linux": {
      "icon": "build/icons"
    }
  },
  "dependencies": {
    "agora-electron-sdk": "2.3.4-hotfix.9",
    "axios": "^0.18.0",
    "better-scroll": "^1.15.2",
    "echarts": "^4.4.0",
    "element-ui": "^2.12.0",
    "less": "^3.10.3",
    "less-loader": "^5.0.0",
    "qs": "^6.5.2",
    "swiper": "^4.3.5",
    "vue": "^2.5.16",
    "vue-calendar-component": "^2.8.2",
    "vue-cropper": "^0.2.9",
    "vue-electron": "^1.0.6",
    "vue-image-crop-upload": "^2.3.3",
    "vue-lazyload": "^1.3.3",
    "vue-resize-sensor": "^2.0.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "vuex-electron": "^1.0.0",
    "wangeditor": "^3.1.1"
  },
  
  "devDependencies": {
    "ajv": "^6.5.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "babili-webpack-plugin": "^0.1.2",
    "cfonts": "^2.1.2",
    "chalk": "^2.4.1",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.1.6",
    "css-loader": "^0.28.11",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^5.0.12",
    "electron-builder": "^20.19.2",
    "electron-debug": "^1.5.0",
    "electron-devtools-installer": "^2.2.4",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "0.4.0",
    "multispinner": "^0.2.1",
    "node-loader": "^0.6.0",
    "style-loader": "^0.21.0",
    "url-loader": "^1.0.1",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^15.2.4",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.15.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.3"
  },
  "agora_electron": {
    "prebuilt": true,
    "electron_version": "5.0.8",
    "platform": "darwin"
  }
}

**Comment by w493189140** [comment]
node 版本有啥要求  
![image](https://user-images.githubusercontent.com/22770789/69209795-910f0480-0b93-11ea-92e0-ced2c7bf4552.png)

**Comment by plutoless** [comment]
windows platform不要填darwin，可以去掉
node版本没问题

**Comment by w493189140** [comment]
![image](https://user-images.githubusercontent.com/22770789/69210223-fe6f6500-0b94-11ea-96ac-8f28df8a2509.png)

**Comment by w493189140** [comment]
手动引入  直接下载sdk  然后引入  也不行  我的操作姿势有问题？
![image](https://user-images.githubusercontent.com/22770789/69212291-dafbe880-0b9b-11ea-9f7e-c0d8dbc503cf.png)

**Comment by w493189140** [comment]
现在貌似是装上了   执行顺序  先安装其他包  然后再安装sdk  然后再安装electron  顺序还不能乱 但是现在还是在报错 报错信息 A dynamic link library (DLL) initialization routine failed.
![image](https://user-images.githubusercontent.com/22770789/69219426-c45e8d00-0bad-11ea-8d56-2f6e757d1292.png)

**Comment by w493189140** [comment]
安装sdk 会把electron remove掉  这个sdk很怪啊

**Comment by plutoless** [comment]
@w493189140 你的electron版本是5.0.8吗？

**Comment by plutoless** [comment]
我们sdk不会把electron remove掉的

**Comment by w493189140** [comment]
electron 版本需要啥？？？不是3.0.6  搞5.0.8直接跑不起来

**Comment by w493189140** [comment]
3.0.6报错信息
![image](https://user-images.githubusercontent.com/22770789/69234888-3396aa00-0bcb-11ea-937c-04e54f3bf4e4.png)
5.0.8 无法启动项目
![image](https://user-images.githubusercontent.com/22770789/69235629-ce43b880-0bcc-11ea-8fb9-2d888ed62999.png)

**Comment by w493189140** [comment]
开发electron  对系统有什么要求 我现在是win10 x64  是不是对系统支持性不好 各种报错 ？

**Comment by plutoless** [comment]
上面的错误看起来是你们自己webpack的错误，和我们sdk无关。
如果你只有3.0.6能跑起来，可以把package json里面的agora_electron配置里的版本也改成3.0.6后重新npm install一下

**Comment by w493189140** [comment]
目前所有配置都是3.0.6
![image](https://user-images.githubusercontent.com/22770789/69305272-5cb44a80-0c5e-11ea-9289-f89d67d3149a.png)

**Comment by plutoless** [comment]
你们是自己重新搭的项目吗？用的是普通的webpack? webpack有对.node文件做什么配置吗？

**Comment by w493189140** [comment]
![image](https://user-images.githubusercontent.com/22770789/69841538-91498700-129a-11ea-87b6-e9c903ce418a.png)

**Comment by w493189140** [comment]
你这边能给个具体要求  electron 版本  node版本  以及SDK版本 什么情况下才能不报错跑起来项目  win10 X64  系统

**Comment by plutoless** [comment]
你上面的错误是electron要装32位的，npm install electron --arch=ia32

**Comment by plutoless** [comment]
electron版本 5.0.8 32位，node版本无所谓，sdk版本2.9.2-hotfix.2，package.json里agora_electron里的版本配置和electron版本一致

**Comment by w493189140** [comment]
![image](https://user-images.githubusercontent.com/22770789/69842309-ac69c600-129d-11ea-842f-cf24e8e9ed08.png)
装上electron 32 还是报错

**Comment by w493189140** [comment]
![image](https://user-images.githubusercontent.com/22770789/69842405-1a15f200-129e-11ea-91b8-b3a09b350e00.png)

**Comment by w493189140** [comment]
官方demo  只加了appID 其他啥都没改

**Comment by plutoless** [comment]
是不是global也装了electron? 可以看下which electron返回的结果是什么

**Comment by plutoless** [comment]
是不是global也装了electron? 可以看下which electron返回的结果是什么

**Comment by w493189140** [comment]
which 这个命令windows 不支持吧   还有我把global的electron也装了32   还是不行  报错信息一样

**Comment by plutoless** [comment]
这边有声网的客户支持群吗？你让他们直接拉一下我，直接沟通吧，效率高一点

**Comment by w493189140** [comment]
好的

**Comment by plutoless** [comment]
已修复
