### ISSUE TITLE
调用setLiveTranscoding方法后会与devtool断开并断流?不调用这个方法的话能正常运行

### ISSUE THREAD

**Issue by ClaytonPetrosian** [AgoraIO-Community/Agora-Electron-Quickstart#19]
![image](https://user-images.githubusercontent.com/17127196/72401895-5aff9280-3788-11ea-9fe4-c89f673e2e00.png)
![image](https://user-images.githubusercontent.com/17127196/72401904-5fc44680-3788-11ea-8a84-57d5df0b44ae.png)

**Comment by ClaytonPetrosian** [comment]
使用react实现的话会是这样子
![image](https://user-images.githubusercontent.com/17127196/72415036-901edb80-37ae-11ea-84d8-a1a9c179785a.png)

**Comment by plutoless** [comment]
这个错的意思是参数给的不正确
可以参考这里
https://github.com/AgoraIO/Electron-SDK/blob/bf46663e8c80b95e6543e378cbbbfbd98e4298f9/example/src/renderer/App.js#L398

**Comment by ClaytonPetrosian** [comment]
可以了谢谢
