### ISSUE TITLE
Vue+Electron5.0.8白屏

### ISSUE THREAD

**Issue by Heleninsa** [AgoraIO-Community/Agora-Electron-Quickstart#20]
[warn] kq_init: detected broken kqueue; not using.: No such file or directory
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: No such file or directory
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

  "agora_electron": {
    "electron_version": "5.0.8",
    "prebuilt": true
  }

**Comment by Heleninsa** [comment]
修改为
  "agora_electron": {
    "electron_version": "4.2.8",
    "prebuilt": true
  }
报错： Electron could not be found. No hard resets for you!

**Comment by plutoless** [comment]
fixed in https://github.com//issues/20

**Comment by TheHtmler** [comment]
> fixed in https://github.com//issues/20

windows端跑的正常，但是mac跑起来就会报那两个warn，然后页面就卡住了

**Comment by plutoless** [comment]
@TheHtmler console log 方法发我看下吗？我上fix的时候自己跑过是没问题的
