### ISSUE TITLE
项目mac上跑起来会卡住，有两个warn

### ISSUE THREAD

**Issue by TheHtmler** [AgoraIO-Community/Agora-Electron-Quickstart#21]
```
[warn] kq_init: detected broken kqueue; not using.: No such file or directory
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
```
导致我打开官方demo，我页面直接卡住

**Comment by plutoless** [comment]
这个错误不影响的，麻烦看一下chrome console里有没有什么错误

**Comment by VeraWei** [comment]
> 这个错误不影响的，麻烦看一下chrome console里有没有什么错误

我也遇到了这个问题，导致console面板断联，不知是何原因？
![image](https://user-images.githubusercontent.com/7732663/90317954-bee66700-dee1-11ea-91b8-7d1cfeab228c.png)

**Comment by plutoless** [comment]
@VeraWei 你是在跑npm run dev的时候崩溃的吗？mac下不要在vscode之类的编辑器的命令行里跑npm run dev，用mac自带的terminal跑

**Comment by VeraWei** [comment]
> @VeraWei 你是在跑npm run dev的时候崩溃的吗？mac下不要在vscode之类的编辑器的命令行里跑npm run dev，用mac自带的terminal跑

是的，好的我试一下。
