### ISSUE TITLE
为什么我安装完sdk引用运行的时候报这个错误呢Uncaught Error: Loading non-context-aware native module in renderer: '.../node_modules/agora-electron-sdk/build/Release/agora_node_ext.node', but app.allowRendererProcessReuse is true.

### ISSUE THREAD

**Issue by wu0211** [AgoraIO-Community/Agora-Electron-Quickstart#28]
![image](https://user-images.githubusercontent.com/34398833/81476727-05bf2380-9246-11ea-8e99-beeba75bddc6.png)

**Comment by plutoless** [comment]
这边是有什么原因打开了allowRendererProcessReuse吗？

**Comment by wu0211** [comment]
> 这边是有什么原因打开了allowRendererProcessReuse吗？

这个解决了，把electron 降到5.0.8 就行了
