### ISSUE TITLE
electron 生产模式报Cannot find module 'agora-electron-sdk'

### ISSUE THREAD

**Issue by wu0211** [AgoraIO-Community/Agora-Electron-Quickstart#29]
Uncaught Error: Cannot find module 'agora-electron-sdk'
Require stack:

![image](https://user-images.githubusercontent.com/34398833/81524033-5d62a980-9382-11ea-8924-e43ab74a38ad.png)

**Comment by book12085** [comment]
你好  请问一下您是如何解决的呢？  我目前也遇到了相同的问题。

**Comment by lowequincy** [comment]
我也遇到了 求解
