### ISSUE TITLE
打包在window 上运行提示的

### ISSUE THREAD

**Issue by wu0211** [AgoraIO-Community/Agora-Electron-Quickstart#30]
![image](https://user-images.githubusercontent.com/34398833/81637893-1344fb00-944a-11ea-9ef6-75043dedf638.png)

**Comment by plutoless** [comment]
打包的时候arch要选择32位

**Comment by wu0211** [comment]
@plutoless  问一下，这个sdk 支持electron 最新版的包么

**Comment by plutoless** [comment]
目前版本预编译包还没有支持到，非预编译包目前有些问题，3.0.1会修复，可以期待下个版本，大概月底

**Comment by wu0211** [comment]
> 目前版本预编译包还没有支持到，非预编译包目前有些问题，3.0.1会修复，可以期待下个版本，大概月底

希望尽快吧，不要electron 一些新的api 都没法用
