### ISSUE TITLE
Error running sample: "agora_node_ext.node is not a valid Win32"

### ISSUE THREAD

**Issue by isMeCoder** [AgoraIO-Community/Agora-Electron-Quickstart#4]
Steps to repro:

Clone repo.

- `yarn run install`
- `yarn run dev`

Electron launches, with a console error that says 
"Uncaught Error: \\(--REDACTED--)\Agora-Electron-Quickstart-master\node_modules\agora-electron-sdk\build\Release\agora_node_ext.node is not a valid Win32 application\\?\(--REDACTED--)\Agora-Electron-Quickstart-master\node_modules\agora-electron-sdk\build\Release\agora_node_ext.node"

I verified that agora_node_ext.node is in the correct location inside of node_modules\agora-electron-sdk\build\Release

Appreciate your help solving this so that we can continue integrating Agora into our existing electron App.

agora-electron-sdk version: 2.0.7-rc.6

**Comment by menthays** [comment]
Our sdk only support Win32 so you have to install electron for Win32 by

`npm install -D --arch=ia32 electron`

Besides, `yarn` does not support commands like this. So you would better use `npm` to reinstall your whole node_modules or install electron separately and move it to your node modules manually.

**Comment by isMeCoder** [comment]
Thanks menthays, that solved it.
