### ISSUE TITLE
Agora Premium App crashing

### ISSUE THREAD

**Issue by silarvaibhav** [AgoraIO-Community/Agora-Electron-Quickstart#43]
I am running electron example on Mac Catalina, When app try to get camera following warning comes in console crashing app:

[warn] kq_init: detected broken kqueue

When below code executes app crashes App.js:

      this.setState({
        videoDevices: rtcEngine.getVideoDevices(),
        audioDevices: rtcEngine.getAudioRecordingDevices(),
        audioPlaybackDevices: rtcEngine.getAudioPlaybackDevices(),
      })

App ran successfully for the first time. And error was coming after that.

No camera/audio devices are being shared at this point.
Any help will be appreciated.

**Comment by plutoless** [comment]
App ran successfully for the first time -> does this mean you can see the video for at least one time? or not at all? how are you running the demo? npm run dev?

**Comment by silarvaibhav** [comment]
Correc, I can see others video. I was using npm run dev

**Comment by plutoless** [comment]
can you maybe call separately to see which api is crashing your app? How can i reproduce this in quickstart example?

**Comment by silarvaibhav** [comment]
rtcEngine.getVideoDevices() is crashing app. In one of my folder it's working fine. Don't know may be because of npm package(electron,agora sdk) version installed. Will try to figure it out.

**Comment by plutoless** [comment]
if you are running "npm run dev", make sure you are not starting the app from editor terminal (vscode for example)
if you are running released app, make sure you have the entitlements file properly configured.

**Comment by silarvaibhav** [comment]
was running from vscode. Working now.
Thanks for help
