### ISSUE TITLE
Nothing is show in the Electron Window

### ISSUE THREAD

**Issue by yaojingguo** [AgoraIO-Community/Agora-Electron-Quickstart#5]
I used `npm run dev` to start the Electron App. But nothing is shown in the window as shown in the following screenshot:

<img width="1403" alt="2018-09-23 3 31 35" src="https://user-images.githubusercontent.com/516386/45925356-08241b00-bf46-11e8-8243-ef712e11f933.png">

Is this expected behaviour? Or something is wrong.

**Comment by menthays** [comment]
Can you show us the log during running `npm run dev`. It seems that webpack failed  to build static assets.

**Comment by yaojingguo** [comment]
I find the cause of my problem. I am using ShadowSocks in `Global Mode`. After I put ShadowSocks in `Auto Proxy Mode`, the UI shows up.
