### ISSUE TITLE
一直在不断刷新，是什么原因？

### ISSUE THREAD

**Issue by Edric-Li** [AgoraIO-Community/Agora-Electron-Quickstart#50]

**Comment by Shealtiel-Li** [comment]
mac平台，直接运行demo（Agora-Electron-React）

**Comment by Shealtiel-Li** [comment]
打包以后可以运行。但是不打包，直接执行yarn dev 一直在刷新

**Comment by plutoless** [comment]
@Shealtiel-Li 用Npm试下

**Comment by Landy0524** [comment]
mac平台，直接运行demo（Agora-Electron-Vue） 执行 npm run dev ，出现一样的问题

**Comment by Landy0524** [comment]
![Uploading image.png…]()

**Comment by Landy0524** [comment]
[64952:1119/184036.136773:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)

**Comment by plutoless** [comment]
https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/issues/50
@Landy0524 应该修复了，是因为监听目录有日志文件的关系

**Comment by shi-nn** [comment]
mac平台，直接运行demo（Agora-Electron-Vue） 执行 npm run dev
一直在不断刷新  并没有修复
