### ISSUE TITLE
Audio Indicator Test

### ISSUE THREAD

**Issue by silarvaibhav** [AgoraIO-Community/Agora-Electron-Quickstart#52]
On electron, is there any provision in Agora to create visual audio indicator test for mic testing. Since we do not have access to audio stream we are not able to create visual sine wave. 
startEchoTestWithInterval in Agora Electron API doen not work as it doesnt return stream.

We need to create a visualizer for  user mic testing. Any pointer will be appreciated

Thanks

**Comment by plutoless** [comment]
@silarvaibhav 
use enableAudioVolumeIndication and audioVolumeIndication callback for volume to display visual wave.

**Comment by silarvaibhav** [comment]
Thanks.
