### ISSUE TITLE
windows下 屏幕共享问题

### ISSUE THREAD

**Issue by sihuayin** [AgoraIO-Community/Agora-Electron-Quickstart#61]
用官方的项目 Agora-Electron-Premium 启动，选择屏幕共享，在弹出选中中选择 chrome浏览器，出现的共享内容是错误的。如图
![image](https://user-images.githubusercontent.com/1635996/105131030-1c32b400-5b23-11eb-901c-c3f1b9247892.png)

**Comment by plutoless** [comment]
@sihuayin 你好，我试了下是好的，您能截个图给我看下您选择的是哪个窗口吗
![image](https://user-images.githubusercontent.com/471561/106373641-99c5b200-63b6-11eb-90eb-56b7bd81488e.png)

**Comment by sihuayin** [comment]
@plutoless 你好，是这样的：
1. 选择 “Screen Share”
![image](https://user-images.githubusercontent.com/1635996/106403343-1d3fdb80-6469-11eb-853c-cbb0cafd1c67.png)
2. 弹出框是当前打开的应用列表
![image](https://user-images.githubusercontent.com/1635996/106403367-482a2f80-6469-11eb-93a4-815b0140d44d.png)
双击选择chrome浏览器
![image](https://user-images.githubusercontent.com/1635996/106403387-65f79480-6469-11eb-8e60-461315fd7902.png)
3. 显示出共享内容，但是内容是错误的
![image](https://user-images.githubusercontent.com/1635996/106403407-84f62680-6469-11eb-8bc6-796477ca4452.png)
4. 正确的浏览器内容是：
![image](https://user-images.githubusercontent.com/1635996/106403416-97706000-6469-11eb-81af-078c25c3613e.png)


此问题只是出现在windows环境下，mac环境下 是正确的。

**Comment by dongyifan** [comment]
由于 Windows 系统的限制，Chrome 这种用硬件加速的窗口无法很容易的拿到窗口内容，所以目前我们对 Chrome 这种窗口，是先进行屏幕截图，然后再把 Chrome 所在区域抠图的方式共享，所以如果 Chrome 上有窗口遮挡就会把遮挡的窗口共享出去。如果要共享 Chrome，需要把 Chrome 在屏幕上置顶才行。后续会寻找更好的方案解决这个问题。

**Comment by sihuayin** [comment]
@dongyifan 按照你说的方式，是可以的。如果共享的chrome上面有窗口，就会遮挡住chrome的页面内容。暂时的使用方式是 ：要求chrome位于屏幕顶层。
