### ISSUE TITLE
Obsolete code in Agora-Electron-Premium/scripts/writeAppId.js

### ISSUE THREAD

**Issue by merlinran** [AgoraIO-Community/Agora-Electron-Quickstart#65]
`APP_ID` no longer exists in the target JS file

https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/blob/3585d99b54afd58cba1c37e985faee0f13dabb89/Agora-Electron-Premium/scripts/writeAppId.js#L8

**Comment by plutoless** [comment]
yes. that is a CI script. i believe you can simply ignore it.

**Comment by plutoless** [comment]
this should be fine. the script was used in CI only. currently CI is not using this script.

**Comment by plutoless** [comment]
the script file was removed.
