### ISSUE TITLE
gora_node_ext.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by zhangdexin** [AgoraIO-Community/Agora-Electron-Quickstart#7]
ELECTRON_ASAR.js:160 Uncaught Error: \\?\D:\pro\Agora\Agora-Electron-Quickstart\node_modules\_agora-electron-sdk@2.4.0-beta.2@agora-electron-sdk\build\Release\agora_node_ext.node is not a valid Win32 application.
\\?\D:\pro\Agora\Agora-Electron-Quickstart\node_modules\_agora-electron-sdk@2.4.0-beta.2@agora-electron-sdk\build\Release\agora_node_ext.node
    at process.module.(:60041/anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722)
    at Object.module.(:60041/anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (D:\pro\Agora\Agora-Electron-Quickstart\node_modules\_agora-electron-sdk@2.4.0-beta.2@agora-electron-sdk\js\Api\index.js:5)
    at Object.<anonymous> (D:\pro\Agora\Agora-Electron-Quickstart\node_modules\_agora-electron-sdk@2.4.0-beta.2@agora-electron-sdk\js\Api\index.js:2023)

**Comment by plutoless** [comment]
Electron要装32位 npm install electron —arch=ia32

**Comment by zhangdexin** [comment]
谢谢~

**Comment by ClaytonPetrosian** [comment]
你好，我已经装了32位的了，但还是打开exe文件会报这个错误，步骤是：
npm install electron —arch=ia32 =》npm install => npm dist

**Comment by plutoless** [comment]
npm dist的时候用的electron arch需要在electron builder的配置里指定

**Comment by ClaytonPetrosian** [comment]
是的，npm run dev是可以的，builder配置改成这样后：
"build": {
    "asar": false,
    "files": [
      "build/**/*",
      "main.js",
      "index.html",
      "node_modules/**/*"
    ],
    "mac": {
      "hardenedRuntime": false
    },
    "electronDownload": {
      "platform": "win32",
      "arch": "ia32"
    },
    "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "ia32"
          ]
        }
      ]
    }
  },
![image](https://user-images.githubusercontent.com/17127196/72582784-e7dc5480-391e-11ea-9a58-884d46814b0f.png)
打开exe会报这么一个错误：
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
![image](https://user-images.githubusercontent.com/17127196/72582817-fdea1500-391e-11ea-85ef-4fab23241bf7.png)

**Comment by plutoless** [comment]
用的是哪个项目？我试一把

**Comment by wu0211** [comment]
Agora-Electron-React @plutoless  这个项目，难道在window64 上都无法开发和运行吗，开发的时候npm run dev 都是报错的，但是在mac 环境是没啥问题

**Comment by wu0211** [comment]
![image](https://user-images.githubusercontent.com/34398833/82168061-47a83380-98f0-11ea-9f9c-92c3371e4fde.png)

**Comment by plutoless** [comment]
可以的，确保你的electron是32位就好

**Comment by wu0211** [comment]
> 可以的，确保你的electron是32位就好

npm install -D --arch=ia32 electron 这样有啥问题吗？

**Comment by lowequincy** [comment]
> > 可以的，确保你的electron是32位就好
> 
> npm install -D --arch=ia32 electron 这样有啥问题吗？
 请问这个问题你是如何解决的？

**Comment by plutoless** [comment]
@lowequincy 这边安装32位electron不工作吗?

**Comment by denglouhen** [comment]
> @lowequincy 这边安装32位electron不工作吗?

64位的系统，npm install之后npm run start都是正常的，包括打包dist:win64也是正常的，但是打包dist:win32点开就是报上面那个错误。不知道应该怎么办啊。执行npm install -D --arch=ia32 electron，直接npm run start都是报错的。没人试过吗？
