### ISSUE TITLE
会有回声，这个是要怎么设置吗

### ISSUE THREAD

**Issue by zhangdexin** [AgoraIO-Community/Agora-Electron-Quickstart#8]
两端都是用耳机和麦克接入，然后一端可以听到从另一端传回来的自己的声音，有回声，怎么弄？

**Comment by plutoless** [comment]
把代码里的enableLoopbackRecording注释掉，那个接口是用来做声卡采集的

**Comment by zhangdexin** [comment]
好的  谢谢~

**Comment by yindengli** [comment]
怎么让本地随便播放的音频另一端听不到，除非加入了混音

**Comment by plutoless** [comment]
@yindengli 
https://github.com/AgoraIO-Community/Agora-Electron-Quickstart/blob/45b00851b14535e554a0c7c5b7eae22c3928e304/src/renderer/App.js#L140
删除上面这行就好了

**Comment by yindengli** [comment]
删了，另一端还是能听到

**Comment by plutoless** [comment]
@yindengli 你用耳机也这样？外放可能会被二次采集

**Comment by yindengli** [comment]
谢谢
