### ISSUE TITLE
m1 运行 Agora-Electron-API-Example 报错, 不支持m1

### ISSUE THREAD

**Issue by Wster11** [AgoraIO-Community/Agora-Electron-Quickstart#98]
报错信息
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/20762404/153813073-011ad029-a000-490e-b324-2e0a9f8bf668.png">
sdk版本
<img width="967" alt="image" src="https://user-images.githubusercontent.com/20762404/153813856-7ade8a94-8df3-44f1-b232-4feaff8e9ac0.png">

**Comment by Wster11** [comment]
sdk 3.5.0-rc.3-iris.1123-build.1 可以在m1上运行起来

**Comment by Wster11** [comment]
改为3.5.0-rc.3-iris.1123-build.1版本后， 当有用户加入频道时， demo rtcEngine.subscribe is not function

**Comment by RoJoHub** [comment]
Agora-Electron-API-Example 如果要支持 m1,需要将 electron 改为12.0.0
且
Agora-Electron-API-Example/package.json 里面electron_version改为12.0.0
"agora_electron": {
    "prebuilt": true,
    "electron_version": "5.0.8"
  },

**Comment by Wster11** [comment]
> Agora-Electron-API-Example 如果要支持 m1,需要将 electron 改为12.0.0 且 Agora-Electron-API-Example/package.json 里面electron_version改为12.0.0 "agora_electron": { "prebuilt": true, "electron_version": "5.0.8" },

抱歉，刚才尝试了使用sdk latest，和 electron 12版本， 依然运行不起来，还是上面图片的错误，只有iris的sdk能跑起来

**Comment by Wster11** [comment]
什么问题会导致
file Agora-Electron-API-Example/src/node_modules/agora-electron-sdk/build/Release/agora_node_ext.node 这个返回的不一样呢？

技术支持发我的demo文件里面的electron sdk是支持m1的， 我删掉node_modules 重新yarn, 新安装的包就不支持m1了
